import argparse
import ast
from pathlib import Path
from typing import Dict, Iterable, List, Mapping, Sequence

CONFIG_KEYS: Sequence[str] = (
    "SUPABASE_URL",
    "SUPABASE_ANON_KEY",
    "SUPABASE_KEY",
    "SUPABASE_SCHEMA",
    "BASE_ASSETS_URL",
    "APP_DATA",
    "PIXABAY_API_KEY",
    "PIXABAY_URL",
    "UNSPLASH_ACCESS_KEY",
    "CLOUDFLARE_R2_ENDPOINT",
    "CLOUDFLARE_ENDPOINT",
    "CLOUDFLARE_R2_ACCESS_KEY_ID",
    "CLOUDFLARE_ACCESS_KEY_ID",
    "CLOUDFLARE_ACCESS_KEY",
    "CLOUDFLARE_R2_SECRET_ACCESS_KEY",
    "CLOUDFLARE_SECRET_ACCESS_KEY",
    "CLOUDFLARE_SECRET_KEY",
    "CLOUDFLARE_R2_BUCKET",
    "CLOUDFLARE_BUCKET",
    "CLOUDFLARE_BUCKET_NAME",
    "TTS_AGENT_URL",
    "GEMINI_API_KEY",
    "GEMINI_MODEL",
    "GOOGLE_CLOUD_PROJECT",
    "GOOGLE_CLOUD_LOCATION",
    "GOOGLE_GENAI_USE_ENTERPRISE",
)

DEFAULTS: Mapping[str, str] = {
    "SUPABASE_SCHEMA": "public",
    "APP_DATA": "com.binhcodev.kidscard",
    "PIXABAY_URL": "https://pixabay.com/api/?key=",
    "CLOUDFLARE_BUCKET_NAME": "junedu",
    "TTS_AGENT_URL": "https://api.jun-edu.xyz",
    "GEMINI_MODEL": "gemini-2.5-flash",
    "GOOGLE_CLOUD_LOCATION": "asia-southeast1",
    "GOOGLE_GENAI_USE_ENTERPRISE": "false",
}

ALIASES: Sequence[Sequence[str]] = (
    ("SUPABASE_ANON_KEY", "SUPABASE_KEY"),
    ("CLOUDFLARE_R2_ENDPOINT", "CLOUDFLARE_ENDPOINT"),
    (
        "CLOUDFLARE_R2_ACCESS_KEY_ID",
        "CLOUDFLARE_ACCESS_KEY_ID",
        "CLOUDFLARE_ACCESS_KEY",
    ),
    (
        "CLOUDFLARE_R2_SECRET_ACCESS_KEY",
        "CLOUDFLARE_SECRET_ACCESS_KEY",
        "CLOUDFLARE_SECRET_KEY",
    ),
    ("CLOUDFLARE_R2_BUCKET", "CLOUDFLARE_BUCKET", "CLOUDFLARE_BUCKET_NAME"),
)


def _strip_inline_comment(value: str) -> str:
    quote = ""
    escaped = False
    for index, char in enumerate(value):
        if escaped:
            escaped = False
            continue
        if char == "\\":
            escaped = True
            continue
        if quote:
            if char == quote:
                quote = ""
            continue
        if char in {"'", '"'}:
            quote = char
            continue
        if char == "#" and (index == 0 or value[index - 1].isspace()):
            return value[:index].rstrip()
    return value.strip()


def _parse_env_value(raw_value: str) -> str:
    value = _strip_inline_comment(raw_value)
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        try:
            parsed = ast.literal_eval(value)
        except (SyntaxError, ValueError):
            return value[1:-1]
        if isinstance(parsed, str):
            return parsed
    return value


def read_env_file(path: Path) -> Dict[str, str]:
    values: Dict[str, str] = {}
    if not path.exists():
        return values

    for line in path.read_text(encoding="utf-8-sig").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("export "):
            stripped = stripped[len("export ") :].lstrip()
        if "=" not in stripped:
            continue
        key, raw_value = stripped.split("=", 1)
        key = key.strip()
        if key:
            values[key] = _parse_env_value(raw_value.strip())
    return values


def _apply_aliases(values: Dict[str, str]) -> None:
    for group in ALIASES:
        first_value = ""
        for key in group:
            value = values.get(key, "").strip()
            if value:
                first_value = value
                break
        if not first_value:
            continue
        for key in group:
            values[key] = values.get(key, "").strip() or first_value


def build_config_values(env_values: Mapping[str, str]) -> Dict[str, str]:
    values: Dict[str, str] = {
        key: env_values.get(key, DEFAULTS.get(key, "")).strip()
        for key in CONFIG_KEYS
    }
    _apply_aliases(values)
    return values


def _format_assignment(name: str, value: str) -> str:
    return f"{name}: str = {value!r}"


def render_config(values: Mapping[str, str]) -> str:
    assignments: List[str] = [
        _format_assignment(key, values.get(key, "")) for key in CONFIG_KEYS
    ]
    mapping_rows: Iterable[str] = (
        f"    {key!r}: {key}," for key in CONFIG_KEYS
    )
    return (
        "# Generated by cmd/generate_config.py. Do not edit by hand.\n"
        "\n"
        "import os\n"
        "from typing import Dict\n"
        "\n"
        + "\n".join(assignments)
        + "\n\n"
        "_CONFIG_VALUES: Dict[str, str] = {\n"
        + "\n".join(mapping_rows)
        + "\n"
        "}\n"
        "\n"
        "for _name, _value in _CONFIG_VALUES.items():\n"
        "    if _value:\n"
        "        os.environ.setdefault(_name, _value)\n"
    )


def write_config(env_path: Path, output_path: Path) -> None:
    values = build_config_values(read_env_file(env_path))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_config(values), encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate src/config.py from a local .env file."
    )
    parser.add_argument("--env", default=".env", help="Path to the local .env file.")
    parser.add_argument(
        "--out", default="src/config.py", help="Output Python config module."
    )
    args = parser.parse_args()

    write_config(Path(args.env), Path(args.out))


if __name__ == "__main__":
    main()
